# Generated by Django 5.0.2 on 2024-02-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='phone',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
