# Generated by Django 5.0.2 on 2024-02-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_landing_page', '0002_alter_distributor_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='contact_email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
