# Generated by Django 5.0.2 on 2024-02-18 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_landing_page', '0003_alter_distributor_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countycoverage',
            options={'ordering': ['state', 'county']},
        ),
        migrations.RemoveField(
            model_name='countycoverage',
            name='distributor',
        ),
        migrations.AddField(
            model_name='distributor',
            name='coverage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='b_landing_page.countycoverage'),
        ),
    ]
