# Generated by Django 5.0.2 on 2024-02-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_landing_page', '0004_alter_countycoverage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='coverage',
        ),
        migrations.AddField(
            model_name='distributor',
            name='coverage',
            field=models.ManyToManyField(blank=True, to='b_landing_page.countycoverage'),
        ),
    ]
